import styles from "./styles/page.module.scss";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Le Petit Champ Loin - Accueil",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className={styles.page}>
      <h1>Hello World</h1>
    </main>
  );
}
